#!/usr/bin/env bash
# Configuring your domain zone so that the subdomain www points to your load-balancer IP (lb-01)

sub_domain () {
    if [ -n "$2" ]
    then
        dig "$2" | grep -A1 "ANSWER SECTION" | grep -v "ANSWER SECTION" | awk '{print $NF}'
    else
        dig "$1" | grep -A1 "ANSWER SECTION" | grep -v "ANSWER SECTION" | awk '{print $NF}'
    fi
}

sub_domain "$1" "$2"