#!/usr/bin/env bash
# script to install nginx on your web-01
apt-get -y update
apt-get -y install nginx
service nginx start
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
