#!/usr/bin/env bash
# script to add custom http response header to the http response
apt-get -y update
apt-get -y install nginx

sudo sed -i "s/http {/http {\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

sudo service nginx restart
