#!/usr/bin/env bash
# script to configure HAproxy to send traffic to web-01 and web-02
# distribute requests using a roundrobin algorithm
apt-get -y update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

cat <<EOF > /etc/haproxy/haproxy.cfg
frontend haproxy
    bind *:80
    mode http
    
    default_backend rancidevtech.tech-backend

backend rancidevtech.tech-backend
        balance roundrobin
    server 206461-web-01 3.54.236.25.73:80 check
    server 206461-web-02 3.52.91.178.190:80 check
EOF

sudo service haproxy restart
