#!/usr/bin/env bash
# script to configure HAproxy to send traffic to web-01 and web-02
# distribute requests using a roundrobin algorithm
apt-get -y update

apt-get install --no-install-recommends software-properties-common

add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy

CONFIG_FILE="/etc/haproxy/haproxy.cfg"
INIT_FILE="/etc/default/haproxy"


if [ ! -f "$INIT_FILE" ]; then
    touch "$INIT_FILE"
fi

if [ ! -f "$CONFIG_FILE" ]; then
    touch "$CONFIG_FILE"
fi
echo -e "\nfrontend rancidevtech.tech-frontend \n\tbind *:80 \n\tmode http \n\tdefault_backend rancidevtech.tech-backend \n\nbackend rancidevtech.tech-backend \n\tbalance roundrobin \n\tserver 206461-web-01 54.236.25.73:80 check\n\tserver 206461-web-02 52.91.178.190:80 check" >> "$CONFIG_FILE" 

if grep -qE '^ENABLED=[01]$' "$INIT_FILE"; then
    sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
    echo "ENABLED=1" >> "$INIT_FILE"
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
    service haproxy start
else
    service haproxy restart
fi
