#!/usr/bin/env bash
# script to configure HAproxy to send traffic to web-01 and web-02
# distribute requests using a roundrobin algorithm
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

cat <<EOF > /etc/haproxy/haproxy.cfg
frontend rancidevtech.tech-frontend
    bind *:80
    mode http
    
    default_backend rancidevtech.tech-backend

backend rancidevtech.tech-backend
    balance roundrobin
    server 206461-web-01 3.54.236.25.73:80 check
    server 206461-web-02 3.52.91.178.190:80 check
EOF

if grep -q "ENABLED=0" /etc/default/haproxy; then
    sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
else
    echo "ENABLED=1" >> /etc/default/haproxy
fi


service haproxy restart
