#!/usr/bin/env bash
#script creates pid file and displays 'To infinity and beyond'
#and handles sigint and sigterm

PID_FILE="/var/run/myscript.pid"

echo $$ > "$PID_FILE"
trap 'echo "I hate the kill command"; rm "$PID_FILE"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$PID_FILE"; exit' SIGQUIT
while true
do
	echo 'To infinity and beyond'
	sleep 2
done
