#!/usr/bin/env bash
# script displays 'To infinity and beyond' indefinitely after sleep cycle,
# then displays 'I am invincible!!!' when receiving sigterm signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo 'To infinity and beyond'
	sleep 2
done
