#!/usr/bin/env bash
# displaying content of /etc/passwd by username, user id, and home directory path,
# for the user

while IFS=: read -r line
do
	echo "$line" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
