#!/usr/bin/env bash
# parsing log file by ip address, http code, and number of occurences,
# from highest occurence to lowest occurence

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
