#!/usr/bin/env bash
# printing 'Best School' 10 times with a 'Hi' after the ninth time

count=0
while [ $count -lt 10 ]
do
	echo 'Best School'
	((count++))
	if [ "$count" -eq 9 ]
	then	
		echo 'Hi'
	fi
done
