#!/usr/bin/bash
#Configure ufw so that it blocks all incoming traffic, except the following T#CP ports:

#    22 (SSH)
#    443 (HTTPS SSL)
#    80 (HTTP)
ufw default deny incoming
ufw allow ssh
ufw allow https
ufw allow http
ufw enable
