#!/usr/bin/env bash
#Bash script configures an Ubunt server with the requirement
#for the localhost to resolve to 127.0.0.2 and facebook.com
#to resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
