#!/usr/bin/env bash
# Requirements:
#    nginx must be running as nginx user
#    nginx must be listening on all active IPs on port 8080
#    You cannot use apt-get remove
#    Write a Bash script that configures the container to fit the above requirements
chmod 777 /etc/nginx/nginx.conf
sed -i 's/user  nginx;/user  www-data;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/nginx.conf
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
service nginx restart
