#!/usr/bin/env bash
# Requirements:
#    nginx must be running as nginx user
#    nginx must be listening on all active IPs on port 8080
#    You cannot use apt-get remove
#    Write a Bash script that configures the container to fit the above requirements
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
pkill -9 apache2
su nginx -c "service nginx restart"
